apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTmpNMk1ETTVOakF3SGhjTk1qVXhNVEl3TURFMU9USXdXaGNOTXpVeE1URTRNREUxT1RJdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTmpNMk1ETTVOakF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRQjdwaEdGTjUrWkxHS2JXVlNwM2J6TXVvVXcrSXBiRXhXdkZmMXBZZUQKNjV3a09GdnF5cld6dmVCQVZ0SWRzZEplSCtqWVNvc2NiY0JkUUpuUWkwUFNvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVhUUjU3UWxFbXYycld5Z2UydWZICnkrUkJDeEF3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnY1V6QzNrOEJ5Z2E0UkJCNTRZOThaRHA2NnA5N2hTbkcKNk51Rnd3Mm0zTzBDSVFDRkZFVFN4RnV1d3psclFieHRtUk1OTUIvcEZPMkJjWEJDekJmNnd3dVZMZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.1.8:55197
  name: k3d-julo-cluster
- cluster:
    certificate-authority: /Users/macbook/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 20 Nov 2025 18:02:30 GMT
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://127.0.0.1:53237
  name: minikube
contexts:
- context:
    cluster: k3d-julo-cluster
    user: admin@k3d-julo-cluster
  name: k3d-julo-cluster
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: admin@k3d-julo-cluster
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJZDR2T1VFZjY2OTB3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOell6TmpBek9UWXdNQjRYRFRJMU1URXlNREF4TlRreU1Gb1hEVEkyTVRFeQpNREF4TlRreU1Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJCODVKT0NKL1hNcURlQUoKYWZ4UGplY3NwSzlVTzkzUDNLL2tnZ2lYVUtlNUNBeXVRWlZrU3FzaEhhWThiaURoNUcvMXQzd29yc1B6NVE4Mgp5SkRtOGxXalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUmdHL1Q3a1RXc0F4ZVUraDBkR29mZWFtVURFakFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlBKzg1cGFkSERFSEt0WE52T2VDOVBUaVdvTGFyQmdqNnhwNnBLVmozb2d3UUlnWkJMamVqd3RrQS9GRUNadAo4Tms4dUlONjhGb1dQUnFVbzNEdWRhQXVVNUE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTmpNMk1ETTVOakF3SGhjTk1qVXhNVEl3TURFMU9USXdXaGNOTXpVeE1URTRNREUxT1RJdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTmpNMk1ETTVOakF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRMHpWbVdDd0NnSVVKTFdPOFhmbUJxOGlhaWh1R1lucmdGZnNVbmFmSW0KcHZOVllXRGZ6SXc0dytSQkV6N3pKaEYrQmFEbUVYV1FzQm1OeUVvTi9GQStvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVlCdjArNUUxckFNWGxQb2RIUnFICjNtcGxBeEl3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU5Bamt5bzJJQUNtMlRHU3BhUEVndTh6d2x2RG1zT28KcnprOUdhWS93cTVKQWlFQTBMaTVYc2YybkQwdWVubit6SUNsWGpsSWU1Zk8vZWc1TitxemVkT0U0M0k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUw5enAyUCt6UHpBS0Y1TnZxSzk4WGVmaXZMdFRqQWQwWlVzZHdCMENLSThvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSHprazRJbjljeW9ONEFscC9FK041eXlrcjFRNzNjL2NyK1NDQ0pkUXA3a0lESzVCbFdSSwpxeUVkcGp4dUlPSGtiL1czZkNpdXcvUGxEemJJa09ieVZRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
- name: minikube
  user:
    client-certificate: /Users/macbook/.minikube/profiles/minikube/client.crt
    client-key: /Users/macbook/.minikube/profiles/minikube/client.key
